import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

def send_email_with_resume(
    to_email: str,
    subject: str,
    body: str,
    resume_path: str,
    email_user: str,
    email_pass: str
):
    """Constructs and dispatches a MIME email with a PDF attachment via Gmail SMTP."""
    
    # Create top-level email container
    msg = MIMEMultipart()
    msg['From'] = email_user
    msg['To'] = to_email
    msg['Subject'] = subject

    # Attach the plain-text body generated by Gemini
    msg.attach(MIMEText(body, 'plain'))

    # Encode and attach the PDF resume if it exists
    if resume_path and os.path.exists(resume_path):
        with open(resume_path, "rb") as attachment:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())
            
        encoders.encode_base64(part)
        filename = os.path.basename(resume_path)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename= {filename}",
        )
        msg.attach(part)
    elif resume_path:
        print(f"⚠️ Warning: Resume file at '{resume_path}' not found. Sending without attachment.")

    # Authenticate and transmit via Gmail SMTP
    with smtplib.SMTP('smtp.gmail.com', 587) as server:
        server.starttls()
        server.login(email_user, email_pass)
        server.send_message(msg)

